# Generated by Django 3.0.6 on 2020-06-01 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football_analysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
